In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3,4,5])

In [3]:
a1

array([1, 2, 3, 4, 5])

In [4]:
a2 = np.array([[1,2,3],
              [4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a3 = np.array([[[1,2,3],
             [4,5,6],
              [7,8,9]],
             [[10,11,12],
             [13,14,15],
             [16,17,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [6]:
import pandas as pd

In [7]:
dataset = pd.DataFrame(a2)
dataset

0  1  2
0  1  2  3
1  4  5  6

In [8]:
low_var = np.array([2,4,6,8,10,12,14])
np.var(low_var)

16.0

In [9]:
np.std(low_var)

4.0

In [10]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [12]:
reshape_a2 = a2.reshape(2,3,1)
reshape_a2

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [13]:
#Transposing of array same as transpose of a matrix
a2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### Dot product in numpy is Cross product of matrix in maths and simple multiplication is dot product of matrix in maths